// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "confPassword": "admin",
    "role": "admin"
}

###
// Get All Users
GET http://localhost:5000/users/

###
// Get Single User
GET http://localhost:5000/users/c903d5c1-11ea-4fc9-a558-5c551dc26152

### update a user 
PATCH  http://localhost:5000/users/c903d5c1-11ea-4fc9-a558-5c551dc26152
Content-Type: application/json

{
    "name": "Muhammad Rizki Syahputra",
    "email": "riski@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

### delete a user 
DELETE http://localhost:5000/users/53b1dadd-8f19-48dd-a6a7-623e5eca8c53

### login a admin 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

### login a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "riski@gmail.com",
    "password": "123456"
}


### get me
GET http://localhost:5000/me

### logout 
DELETE http://localhost:5000/logout

# menit 56
