// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "riski user",
    "email": "riskiUser@gmail.com",
    "password": "user",
    "confPassword": "user",
    "role": "user"
}

###
// Get All Users
GET http://localhost:5000/users/

###
// Get Single User
GET http://localhost:5000/users/d79f2864-f67c-49d4-8bc6-dcfe20bacd0d

### update a user 
PATCH  http://localhost:5000/users/1cf83ffa-94a2-4b86-b3c5-34460813b6ba
Content-Type: application/json

{
    "name": "riski admin",
    "email": "riskiAdmin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

### delete a user 
DELETE http://localhost:5000/users/d79f2864-f67c-49d4-8bc6-dcfe20bacd0d

### login a admin 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "riskiAdmin@gmail.com",
    "password": "admin"
}

### login a user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "riskiUser@gmail.com",
    "password": "user"
}


### get me
GET http://localhost:5000/me

### logout 
DELETE http://localhost:5000/logout

### Get All Products
GET http://localhost:5000/products/


### Get Single Products
GET http://localhost:5000/products/9cd73153-5021-47a0-bff5-6ebe8985d2cc


### POST Data Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 4 #User",
    "price": 15
}

### Update a Product 
PATCH  http://localhost:5000/products/9cd73153-5021-47a0-bff5-6ebe8985d2cc
Content-Type: application/json

{
   "name": "Product 1 updated",
  "price": 110
}